<?php require_once 'engine/init.php'; include 'layout/overall/header_maps.php'; ?>


<div class="BoxContent" style="background-image:url(https://static.tibia.com/images/global/content/scroll.gif);">
<center><h3>Feyrist</h3></center><center><img border="2" src="https://static.tibia.com/images/library/map_feyrist.jpg"></center><br>Feyrist is a peninsula northwest of Roshamuul. It is bordered by high mountains to the southeast and the sea in the other cardinal directions. Deep forests and lush meadows mix up in the area, dotted with lakes, brooks, hills, ravines and groves. The coast consists partly of sandy beaches, partly of grassy shores. Feyrist has a temperate to warm climate, which has led to a lush, verdurous vegetation. Rich green pastures with various wild flowers and thick deciduous forests are dominating the peninsula. Feyrist is inhabited by the fae, who live scattered all over the woods. There is only one bigger settlement, which consists of many fae houses and a magical fountain. The name Feyrist derives from an old fashioned word, meaning "the fairest". Feyrist arose from the mortals’ pleasant dreams. The reclusive magical realm is among the most secret areas of Tibia, characterised by an enchanted environment and pervaded by ancient magic.<br><br>
The fae are mystical creatures that wield magical and elemental powers. They vary greatly in size and appearance. There are different kinds of fae like fauns, pixies, pookas, swan maidens and boogies. Most fae are rather reclusive and live peaceful lives in their secret realm. They do not build any real cities, but inhabit trees, big mushrooms or huge snail shells. There are also tree houses and dwellings made of thick trunks. The fae can shape wood and stone, so even large rocks may become houses. They often decorate their glades and homes with flowers, tendrils and crystals. In general, the fae are benevolent but also flighty and unpredictable creatures. They are more interested in dancing, making music and playing tricks on each other than in fighting, studying or constructing. Fae like sweets, wine, glittering trinkets, lyrics and music.<br>
Nowadays, there are friendly and dark fae in Feyrist. Originally - and for a very long time - all fae were good-natured and devoted to light. However, ever since dark energies have been seeping into the world of Tibia, more and more fae are tainted. They develop cruel and sadistic traits, they are aggressive and attack other fae. </div>

<?php
include 'layout/overall/footer.php'; ?>
