<?php require_once 'engine/init.php'; include 'layout/overall/header_maps.php'; ?>


<div class="BoxContent" style="background-image:url(https://static.tibia.com/images/global/content/scroll.gif);">
<center><h3>Kilmaresh</h3></center><center><img border="2" src="https://static.tibia.com/images/library/map_kilmaresh.jpg"></center><br>Over a thousand years ago, Krailos and Kilmaresh were a contiguous land mass, inhabited by a human civilisation that had established a thriving empire. Due to a major natural disaster, the eastern peninsula was separated from the continent and is now cut off from the rest of the landmass by a strait. On Krailos, the ancient culture was smashed by the ogres and disappeared completely. However, it survived on Kilmaresh and up to this day, it thrives there on a high cultural and economic level. East of the strait that separates Kilmaresh from Krailos, there are mainly dry steppe regions. At the peninsula's centre lies a large mountain range and one can discover small oases and tombs scattered all over the steppe. In addition, there are many rock formations, interveined with blue ore. This ore can be magically crafted into a rare and precious metal that Sapphire Blade members use for their blades. A large river, the Nykri, rises in the central mountains and forms a fork halfway to the sea. Here lies the big city Issavi, the heart of Kilmaresh. The original capital Nuur was destroyed by Suon's Wrath.<br><br>
Not only humans live in Kilmaresh but also the Anuma, magical creatures like sphinxes, lamassu, manticores and gryphons. It is said that the entire continent was once given to them by the gods. But the Anuma conferred the dominance over Kilmaresh to the humans in an effort to let them take responsibility of their own. However, after the religious war between the worshippers of Suon and Fafnar and the cataclysm that severed the continent, the Anuma took the reign over Kilmaresh back - for the humans' own benefit as they said. </div>

<?php
include 'layout/overall/footer.php'; ?>
